micronaut:
  application:
    name: walletService
netty:
  default:
    allocator:
      max-order: 3

#AWS
aws:
  access-key-id: 123
  secret-key: 123
  region: us-east-1
  endpoint: http://localhost:4566
  dynamodb:
    wallet-table: wallet-service.wallets
  sqs:
    transfer-queue: http://localhost:4566/000000000000/transfer-queue.fifo

#SECURITY
security:
  auth:
    enabled: false