
version: '3.8'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main_wallet}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
    environment:
      - TMPDIR=/private/var/folders/v7/_qxvr2d54m565vdm9r8yv_140000gq/T/
      - SERVICES=dynamodb,sqs
      - DEBUG=${DEBUG-}
      - DATA_DIR=/Users/colaborador/localstack/data
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=app://.
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - wallet-service-network

networks:
  wallet-service-network:
    driver: bridge
